import { Component, inject, signal } from '@angular/core';
import { typeWriter } from './typewriter.helper';
import { ArrowRight, CloudUpload, LucideAngularModule } from 'lucide-angular';
import { CreationModel, CreationService } from '../../services/creation-service';
import { form, maxLength, required, submit, FormField } from '@angular/forms/signals';
import { AuthService } from '../../../../core/auth/auth.service';
import { PageLayout } from '../../../../shared/components/page-layout/page-layout';

@Component({
  selector: 'app-create',
  imports: [LucideAngularModule, FormField, PageLayout],
  templateUrl: './create.html',
  styleUrl: './create.css',
})
export class Create {
  private readonly creationService = inject(CreationService);
  private readonly authService = inject(AuthService);
  protected readonly authUser = this.authService.authUser();
  private readonly creationModel = signal<CreationModel>(
    this.creationService.getDefaultCreationModel(),
  );

  protected readonly creationForm = form(this.creationModel, (fieldPath) => {
    required(fieldPath.prompt);
    maxLength(fieldPath.title, 20);
  });

  protected readonly displayedUserGreeting = signal('');
  protected readonly displayedText = signal('');
  protected readonly currentStep = signal<'prompt' | 'title'>('prompt');
  protected readonly isTyping = signal(false);
  protected readonly isThinking = signal(false);

  private readonly userGreeting = `Hi, ${this.authUser?.firstName}!`;
  private readonly greetings = [
    'Time to create a vision. Describe your image...',
    "Let's bring your imagination to life. What should I draw?",
    "A blank canvas is waiting. What's on your mind?",
  ];
  protected readonly icons = {
    arrowRightIcon: ArrowRight,
    cloudUploadIcon: CloudUpload,
  };

  constructor() {
    this.isTyping.set(true);
    // Erster Text
    typeWriter(
      this.userGreeting,
      (g) => this.displayedUserGreeting.set(g),
      () => {
        // Zweiter Text nach kurzer Pause starten
        setTimeout(() => this.setMessage(), 400);
      },
    );
  }

  private setMessage() {
    this.isTyping.set(true);
    const text = this.greetings[Math.floor(Math.random() * this.greetings.length)];
    typeWriter(
      text,
      (t) => this.displayedText.set(t),
      () => {
        this.isTyping.set(false); // Jetzt sind beide Zeilen fertig
      },
    );
  }

  protected async onSetTitle() {
    const promptValue = this.creationForm.prompt().value();
    // Mocking for later with short thinking time (AI Validation)
    this.isThinking.set(true);
    this.isTyping.set(true);
    this.displayedText.set('');

    await new Promise((r) => setTimeout(r, 1500));
    const looksLikeGibberish = promptValue.length < 10 || !promptValue.includes(' ');

    if (looksLikeGibberish) {
      this.isThinking.set(false);
      typeWriter(
        "That's a bit cryptic! Could you describe your vision with a few more words?",
        (t) => this.displayedText.set(t),
        () => this.isTyping.set(false),
      );
    } else {
      this.isThinking.set(false);
      this.currentStep.set('title');
      typeWriter(
        'That sounds like a great vision! Now, what should we call this piece?',
        (t) => this.displayedText.set(t),
        () => this.isTyping.set(false),
      );
    }
  }

  protected onBack() {
    this.currentStep.set('prompt');
    this.displayedText.set('');
    this.resetForm();
    this.setMessage();
  }

  protected onSubmit(event: Event) {
    event.preventDefault();

    if (this.currentStep() !== 'title') {
      return;
    }

    // Mock creation. Later via AI
    submit(this.creationForm, async () => {
      const currentTitle = this.creationForm.title().value();
      const currentPrompt = this.creationForm.prompt().value();

      // If title is empty -> will be generated by AI
      if (!currentTitle || currentTitle.trim() === '') {
        this.isThinking.set(true);
        this.isTyping.set(true);
        this.displayedText.set('');
        console.log(currentPrompt);

        // Simulation of title creation
        await new Promise((r) => setTimeout(r, 1200));
        const magicTitle = 'Neon Dreams';

        this.creationModel.update((model) => ({
          ...model,
          title: magicTitle,
        }));
        this.isThinking.set(false);
        await new Promise<void>((resolve) => {
          typeWriter(
            `I named it "${magicTitle}" for you. Generating now...`,
            (t) => this.displayedText.set(t),
            () => {
              this.isTyping.set(false);
              resolve();
            },
          );
        });
      }

      const finalModel = this.creationModel();
      this.creationService.addCreation(finalModel);
      console.log('Generating Image with:', finalModel);

      // Reset after geneartion
      // this.resetForm();
    });
  }

  private resetForm() {
    this.creationForm().reset();
    this.creationModel.set(this.creationService.getDefaultCreationModel());
  }
}
